### ISSUE TITLE
F0003 - SAY has a problem with trailing junk

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#1]
/* */                                     
INTERPRET 'SAY' ARG(1)                    
                                          
Ready; T=0.01/0.01 15:00:35               
say 100/81                                
1.2345679zABCDEFGHIJKLMNOPQRSTUVWXYZ0123  
Ready; T=0.02/0.04 15:00:41               

This way, there is junk after the result.

/* */                       
SAY 100/81                  
                            
Ready; T=0.01/0.01 15:01:28 
test2                       
1.2345679                   
Ready; T=0.03/0.05 15:01:35 

This is the good answer. Here 'interpret' seems the culprit.

Also:

type test3 exec              
                             
/* */                        
SAY 100/81                   
INTERPRET 'SAY 100/81'       
                             
Ready; T=0.01/0.01 15:06:05  
test3                        
1.2345679XYZ0123456789       
1.2345679XYZ0123456789       
Ready; T=0.02/0.04 15:06:12

**Comment by rvjansen** [comment]
well, the issue title could be changed to: "SAY has a problem with trailing junk"

look at this:
type test1 exec                                 
                                                
/* rexx */                                      
say 'Hello, it is Julian Date' date('j') 'today'
parse version v                                 
SAY 'HELLO VM REXX' V                           
                                                
Ready; T=0.01/0.01 16:34:35                     
type test2 exec                                 
                                                
/* */                                           
SAY 100/81                                      
                                                
Ready; T=0.01/0.01 16:34:41                     

when one runs this, this happens:

test1                                   
Hello, it is Julian Date 20051 today    
HELLO VM REXX bREXX 2.1.8 Feb 13 2020   
Ready; T=0.01/0.03 16:36:33             
test2                                   
1.2345679 is Julian Date                
Ready; T=0.03/0.05 16:36:34             
                                       
the 'is Julian Date' part is from the execution of the previous exec.

**Comment by adesutherland** [comment]
I think this is something to do with print.c line 110 etc.

I.e. only impacts printing of real values (so does "X=100/81; say X 'a';", print as expected).

Question: print.c is a mess and very slow (prints strings character by character). Should we just make a cleaned version for CMS only, getting rid of the defines etc. I mean it is never going back to the BREXX main line anyway ... and will be much easier for future workers to maintain!

What do you think?

**Comment by rvjansen** [comment]
This is exactly what the MVS Brexx crew did; I have doubts about this. I like having things in one repo. We build ooRexx for Windows (686, X86_64 *and* S/390X), Linux, Mac, Sparc etc) from one repository. It is a question of diverging early enough to OS-specific paths.

As we forked already, it is no real issue. I hope someone will put it back together someday.

**Comment by adesutherland** [comment]
I have given the question of defines some thought - and I totally understand your points. 

On balance, I think the changes to make BREXX reentrant for CMS will need lots of tiny changes. The defines will be too complex and just confuse, there is no reason for anyone to take these changes back (modern toolchains just *do* reentrancy!). Therefore I will simplify the files and make it CMS specific as we go.

**Comment by adesutherland** [comment]
There are two problems (I think).

1. A tactical issue with something expecting a null terminated string. We need to fix this early as it is demotivating to see that say does not work! **Work in branch feature/f0003**

2. A strategic issue with non-reentrant global variables. **Work in branch feature/f0004**

**Comment by adesutherland** [comment]
Fixed in feature/f0003 

Ready for retest :-)

**Comment by adesutherland** [comment]
We are still seeing this bug with 1 character strings.

I have tested GCCLIB (BREXX calls "fprintf(f, "%.*s", LLEN(*str), LSTR(*str));") and it is fine.

Need to test LLEN etc. in BREXX.

**Comment by adesutherland** [comment]
fprintf() bug in GCCLIB. Fixed in GCCLIB F0018.
