### ISSUE TITLE
Program can call a label in a second program

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CMS-370-BREXX#12]
The way BREXX handles calls to external REXX programs is:
- When launching a program the program name is marked as a label 
  (Hotfix - check label and change type to EXTERNAL or BUILTIN)
- The single pass compiler will try and matchup calls to labels
- The interpreter then knows what do do when it gets a call
- Unmatched Calls trigger the **Interpreter** to try and load a REXX program. This is then compiled within the same context of the main program. This predicted the defect where a program can call a label in a second program (See code below).
- If a REXX program does not exist an external program is called (this is not implemented in CMS BREXX)
- Implementation of this type pf call - "func"() - is incomplete

The hot fix shows the problem - quite hard to maintain because the logic is not transparent and feels "organic", the hot fix just adds to this. Also separation of programs in the interpreter is not perfect.

TEST1 EXEC

    /* TEST1 */                 
    SAY TEST1            
    SAY TEST2("HELLO") /* This loads tests2 */   
    CALL TEST2BAD        /* And now this label is visible! */
    RETURN 0             

TEST2 EXEC

    /* TEST2 */                        
    PARSE ARG A                  
    SAY TEST2                    
    SAY A                        
    RETURN 1                     
                             
    TEST2BAD: PROCEDURE          
      SAY TEST2BAD                 
    RETURN

_Originally posted by @adesutherland in https://github.com/adesutherland/CMS-370-BREXX/issues/11#issuecomment-607156706_

**Comment by adesutherland** [comment]
Flagged as WONTFIX - awaiting complaints before closing ...

**Comment by rvjansen** [comment]
I wonder what happens if one intended to call an external TEST2BAD. I'll add this to the testcases because we need to know what the other Rexxen do. I am not complaining yet, but let's keep this open.

**Comment by adesutherland** [comment]
Fixed in F0017 (with call type 5)
