### ISSUE TITLE
Date parsing does not work correctly

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#2]
The standard WHENRUBO exec fails to parse the provided date.
WHENRUBO is included in the BREXX distribution in the PROGS directory

**Comment by adesutherland** [comment]
Hopefully we can find a upstream fix?

**Comment by rvjansen** [comment]
will have a look for that. Not sure if it is not the scanf(). I'll start with the test suite and will put Date() first.

**Comment by adesutherland** [comment]
OK - Can you attach WHENRUBO EXEC here? Thanks :-)

**Comment by rvjansen** [comment]
[whenrubo.exec.zip](https://github.com/adesutherland/CMS-370-BREXX/files/4241700/whenrubo.exec.zip)

**Comment by adesutherland** [comment]
Thanks - yep it doesn't work. (And BTW as I fiddled with it - it showed that file access still is flaky!)

**Comment by rvjansen** [comment]
turns out brexx cannot do this on other platforms either. Closing this until we contribute a standards compliant Date() to brexx.

**Comment by adesutherland** [comment]
I am reopening so we can track it. I might try and fix sooner rather than later and see how getting it back ported works in practice.

**Comment by adesutherland** [comment]
Will revisit once we have reviewed and fixed the Date() test results from the Test Suite.

**Comment by adesutherland** [comment]
Note that DATE() in BREXX does not support translation at the moment

**Comment by rvjansen** [comment]
will use the load library mechanism to provide an implementation in Rexx
