### ISSUE TITLE
cms brexx execs not interruptible with HI

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#3]
The standard way of interrupting an exec with HI does not work with the WHENRUBO exec

**Comment by adesutherland** [comment]
Yes ... I have found that when BREXX starts to go wrong it completely shags CMS. I think the console dies ...

**Comment by adesutherland** [comment]
HI,TS,TE Immediate Mod added to VM/370, GCCLIB Support Functions added, BREXX hooks added.

Implemented.
