### ISSUE TITLE
brexx fails on standard rexxcps benchmark

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#38]
brexx has its own rexxcpr.r, which deviates from the standard cps exec, used universally to determine the number of clauses-per-second a particular interpreter/compiler-os-hardware combo can achieve.  This is because brexx cannot run the standard benchmark. With its own version however, the score is high. We ought to fix the bug that makes the standard cps version fail.

**Comment by adesutherland** [comment]
Can you upload a copy of the standard rexxcpr.r? Thanks

**Comment by RexxLA** [comment]
sorry that is REXXCPS. The canonical version is at http://speleotrove.com/misc/rexxcps.rex
