### ISSUE TITLE
F0006 - EXEC file cannot be found with STAT - executions fails

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#4]
File written: REXXVERS EXEC A1 
Ready; T=0.02/0.04 00:36:54 
type rexxvers exec 

/* REXX */ 
PARSE VERSION X 
SAY X 

Ready; T=0.01/0.01 00:37:02 
rexxvers
--→ Cannot find the just edited and saved file
fopen error: file 'STATE REXXVERS *' not found. 
Error 58 running "REXXVERSC": File not found 
Ready; T=0.02/0.03 00:37:09

--→ copy it to another file
copyfile rexxvers exec a version exec a 
Ready; T=0.01/0.01 00:37:47 
version 
bREXX 2.1.8 Aug 6 2010 
Ready; T=0.02/0.03 00:37:52
--→ after the copy IT CAN FIND IT ????
rexxvers 
bREXX 2.1.8 Aug 6 2010 
Ready; T=0.02/0.03 00:39:50
3) Overwrite of storage
DMSABN149T 109 (HEX 00006D) DOUBLEWORDS OF SYSTEM STORAGE HAVE BEEN DESTROYED. RE-IPL CMS. 
CP ENTERED; DISABLED WAIT PSW '00020000 6001F04E'

**Comment by adesutherland** [comment]
Hello Rene! Can you please retest - I think this is fixed in the CMS 2.1.9 version

Also - version - I am thinking the next version should be CMS specific to avoid confusion. I am thinking 0.9.0 - what do you think?

**Comment by adesutherland** [comment]
Yes, generally there is definitely a problem with accessing files stably - I will see if there is a tactical fix!

**Comment by adesutherland** [comment]
Working if=n feature/f0006

**Comment by adesutherland** [comment]
Sub Issue 1 - In rexx.c RxFileLoad() the return code to CMSfileState() should be checked rather than calling fopen(). That way a extra (misleading) error message is avoided.

Main Issue 2 - Upstream in CMSLIB https://github.com/adesutherland/CMS-370-GCCLIB/issues/6#issue-570162774 - a really wierd issue.

**Comment by adesutherland** [comment]
Rene, Fixed and ready for test in f0006.

This has a interim fix (gives a warning message) when running against the current version of GCCLIB but the upstream fix in GCCLIB is done and will work if used

**Comment by adesutherland** [comment]
Fixed
