### ISSUE TITLE
Source Code under BREXX minidisk

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CMS-370-BREXX#5]
The source code in the BREXX user on the six-pack is not updated by the install scripts.

My preference would be to delete the BREXX user / minidisk on the basis that 

- it will make the docker image smaller, 
- people can get the source here and build on cmsuser, 
- most people don't want the source anyway, and 
- having old source is going to be confusing.

What do people think?

**Comment by rvjansen** [comment]
I think we’ll probably submit it to Dave for integration in ‘official’ sixpack and the docker image is something entirely different, so you can leave it out if you want.

**Comment by adesutherland** [comment]
Source coded now added to BREXX disk (including tests)
