### ISSUE TITLE
Function package in search path breaks EXEC to EXEC function calls

### ISSUE THREAD

**Issue by BobBolch** [adesutherland/CMS-370-BREXX#51]
exec wakeprof                                                       
     5 *-*  cmd = '$WAITF'('WAKEUP TIMES A','SMSG')                 
Error 44 running wakeprof, line 5: Function did not return data     
Ready(20044); T=0.02/0.02 17:05:05 

This started working in V 0.9.8 plus  the F0023 fix.

Broken now.

**Comment by adesutherland** [comment]
What seems to be happening is this. If there is a function package is in the search path then REXX EXEC calling REXX EXEC does not work and instead a no return code is thrown

**Comment by adesutherland** [comment]
Fixed in FF0034

**Comment by BobBolch** [comment]
Fixed in F0034. Thank you.
