### ISSUE TITLE
ADDRESS SYSTEM malfunctions

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#58]
Like in the title. Probably root cause of https://github.com/adesutherland/vm-370/issues/10 
Example:
ADDRESS "SYSTEM" "CP QUERY TIME"
or
/* REXX */                                               
TRACE RESULTS                                            
RWDISK = 'A'                                             
ADDRESS SYSTEM 'EXECUTIL QDISK *'                        
DO WHILE QUEUED() > 0                                    
  PARSE PULL . . . . . . DMODE . DLETTER DREST           
  IF RWDISK = '$' & DMODE = 'R/W' THEN RWDISK = DLETTER  
END                                                      
(which is what fails in XXLIST EXEC)

**Comment by BobBolch** [comment]
SYSTEM is not the name of a command environment in CMS.

**Comment by rvjansen** [comment]
Thanks. Good to know, it used to work though. ADDRESS CMS does work.
