### ISSUE TITLE
Multiplication gives wrong result, precision issue

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#59]
The good news is, I finished my CMS level 15/Rexx 4.02 compatible implementation of DATE(). It runs on macOS BREXX.
The bad news is, it fails on VM/370 CMS 6. I traced this down to one multiplication delivering the wrong answer.

This exec:
/* rexx */                       
NUMERIC DIGITS 18                
MICRO = 737787 * 86400 * 1000000 
SAY MICRO

yields 294330368 
while the right answer is 63744796800000000

Odd thing is, I would expect the BREXX implementations to handle this the same manner. But the one on macOS works correctly. (737787 is todays day number since 1-1-0001, we need the microseconds since that date to convert to the different DATE() output options.)

**Comment by rvjansen** [comment]
this is the result of an 'int' multiply in GCC on this platform. "long long" gives an assembler displacement error.
a double gives 63744796800000040.892797 which is a bit hmm but might still work as it is only 41 microseconds off.

**Comment by adesutherland** [comment]
I am working on the maths in BREXX at the moment to fix the TRUNC function.

I was wondering and fearing if there was any arithmetic errors and was going to ask you if you could help with a maths test suite.

BTW I am finding the tests you have done very useful. When I make fundamental changes they pick up errors I add in other functions. Without this it would be VERY frustrating for users as it would feel like no progress was being made!

So far as maths is concerned. Brexx either uses ints (32 bit only on 370) or IBM doubles (hex float) but I suspect not that simple if we peel back GCC/370 layers. 

I am wondering (but don't want to ... laziness) if we should only use double. The logic of moving between Ints and floats is ugly, complex, organic, and must hide errors! Anyway this looks like the bug you have. It is trying to fit an int from a float but the float is just too big.

I think IBM Hex floating point doubles should support 16 significant digits. However I *think* this may be converted between GCCs formats ... because I am seeing errors on the 16th digit (or may be a bug in printf). Anyway I am going to restrict it to 15 significant digits.

I am sorry that 15 digits is not going to support the 18 digits you need, and for BREXX it's a WONTFIX for more than 15 significant digits :-(

Is there anyway to work round this with DATE? Perhaps we can't support microseconds? Or perhaps you can change the formula to factor out the huge multiplication?

**Comment by adesutherland** [comment]
Here is the problem, as you an see it assumes that if the two operands are integers then the result will also fit into the integer size. For addition and subtraction this is OK. For multiplication (and division [1]) we need to promote to a float (and perhaps check if the result is small enough to fit into a integer and covert back).

[1]: Although division would mostly give a real result, so would be surprised if there was an error here, need to check


```
void __CDECL
Lmult(const PLstr to, const PLstr A, const PLstr B) {
    L2NUM(A);
    L2NUM(B);

    if ((LTYPE(*A) == LINTEGER_TY) && (LTYPE(*B) == LINTEGER_TY)) {
        LINT(*to) = LINT(*A) * LINT(*B);
        LTYPE(*to) = LINTEGER_TY;
        LLEN(*to) = sizeof(long);
    } else {
        LREAL(*to) = TOREAL(*A) * TOREAL(*B);
        LTYPE(*to) = LREAL_TY;
        LLEN(*to) = sizeof(double);
    }
} /* Lmult */


```

**Comment by rvjansen** [comment]
I have tried to lift it all to double by adding a .0 to every number and substituting / for % and // but that only goes so far. I managed to get the day number 'about right' but further on it becomes a mess again. It is obvious computers are bad at math. I'll have to look at the algorithm if this has any chance at all.

**Comment by rvjansen** [comment]
Does this help: http://speleotrove.com/decimal/ the 'decnumber' package that provides Rexx arithmetic in ANSI C?

**Comment by adesutherland** [comment]
Note from Bob - detect overflow:

The instructions have similar condition codes set by the fixed point arithmetic operations:

Condition code    
0 - Result is 0
1 - Result less than 0
2 - Result greater than 0
**3 - Overflow**

Add 
Add halfword
Subtract
Subtract halfword

For the unsigned (logical) instructions

Condition code
0 - Result is zero, no cary
1 - Result is not zero, no carry
2 - result - zero with carry
3 - result is not zero, with carry

Add Logical
Subtract Logical

The condition code mask in the BRANCH instruction is:

Instruction bit
8 9 10 11  
Mask position value
8 4 2 1
Condition code
0 1 2 3

For overflow, Condition code 3 is tested by Mask position 1 
(CC=2 is MASK 2, CC=1 is MASK 4. CC=0 is mask 8.)

To add two registers and branch on Overflow:

**AR  R1,R2
BC  1,OVERFLOW**

**Comment by rvjansen** [comment]
I made an example of how to do the date multiplication in s/370 asm:

`         PRINT NOGEN                                                     
MULT     CSECT                                                           
         USING MULT,R12                                                  
         LR    R12,R15                                                   
         ST    R14,SAVRET                                                
         B     AFTER                                                     
EYEC     DC    CL13'MULT EYECATCH'                                       
AFTER    PACK  PSECS,ZSECS                                               
         PACK  PMILL,ZMILL                                               
         PACK  PDAYS,ZDAYS                                               
         ZAP   PRESULT,PMILL                                             
         MP    PRESULT,PSECS                                             
         MP    PRESULT,PDAYS                                             
         MVC   RESULT(32),MASK                                           
         ED    RESULT,PRESULT                                            
         LINEDIT TEXT='................................',              * 
               SUB=(CHARA,RESULT),RENT=NO                                
         L R14,SAVRET                                                    
         BR R14                                                          
SAVRET   DC    F'0'                                                      
PMILL    DS    PL8                                                       
ZMILL    DC    Z'1000000'              A MILLION                         
PSECS    DS    PL8'0'                                                    
ZSECS    DC    Z'86400'                SECONDS A DAY                     
ZDAYS    DC    Z'737801'               RATA DIE DAY NUMBER               
PDAYS    DS    PL8'0'                                                    
MASK     DC    X'40202020202020202020202020202020'                       
         DC    X'20202020202020202020202020202020'                       
PRESULT  DC    PL16'0'                                                   
RESULT   DC    CL32' '                                                   
         REGEQU                                                          
         END                                                             `

This runs as-is with todays date number. Packed Decimal can go to 31 digits. Do we know if the C compiler can do Packed Decimal?

**Comment by adesutherland** [comment]
"fixed" in F0043 (can't improve precision to 18 digits - but at least it gives the right answer to the maximum precision (14 digits)

**Comment by mgrossmann** [comment]
quick test:

```
Ready(brexx);                     
numeric digits 18                 
Ready(brexx);                     
MICRO = 737787 * 86400 * 1000000  
Ready(brexx);                     
say micro                         
63744796800000000                 
Ready(brexx);                     
```

**Comment by RossPatterson** [comment]
FYI, the `tests\date_.exec` test always fails in test #3 trying to process basedate 3652058 (_aka_ 9999-12-31).  This appears to be essentially the same issue @rvjansen  was trying to deal with at the top of this issue.
