### ISSUE TITLE
Uptodate in mkbrexx needs to look on A disk

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CMS-370-BREXX#6]
For some reason GCC builds on A disk which must be a change since mkbrexx was done.

Anyway just need to get it to check uptodate on the A disk

**Comment by rvjansen** [comment]
well I'll be happy as soon as we can convert this to Rexx. I put in the extra &DISK = A but did not see the uptodate.

**Comment by adesutherland** [comment]
Updated in F0002 in develop branch
