### ISSUE TITLE
After install of Release v0.9.11 binaries DMSREX not found

### ISSUE THREAD

**Issue by marXtevens** [adesutherland/CMS-370-BREXX#64]
I followed the instructions for the binary install, and entered all the commands manually, as herccontrol is not installed on my Linux system. GCCLIB was also installed and a new CMS segment was generated. REXXTEST won't execute. Please note there are missing names identified during the run of SYSPROF EXEC.

Suggestions as to what I should be looking for? What files would be needed to help with diagnosis?

> L MAINT
> ENTER PASSWORD:
>  
> DASD 190 LINKED R/W; R/O BY 003 USERS
> DASD 194 LINKED R/W; R/O BY 002 USERS
> DASD 19E LINKED R/W; R/O BY 002 USERS
> FILES: 005 RDR, 107 PRT,  NO PUN
> LOGON AT 20:28:06 GMT THURSDAY 02/11/21
> CMS VERSION 6.0 - 03/11/18 19:50
>  
> Y (19E) R/O
> GCCLIB Version 0.8.3
> GCC ANCHOR Address is 0xe9b000 saved in NUCON at 0x468
> THE FOLLOWING NAMES ARE UNDEFINED:
>  STDIN    STDERR   GETCHAR  @@SIGIGN STDOUT   PUTCHAR
> SYSPROF Error loading BREXX with RESLIB
> U (19D) R/O
> B (094) R/O
> D (194) R/O
> E (294) R/O
> F (394) R/O
>  
> +-----------------------------------------------------------------------------+
> |          Welcome to VM/370 and VM/380 "SixPack" version 1.3!                |
> +-----------------------------------------------------------------------------+
>  
> For a list of CMS commands, type HELP CMSCMDS.  For a list of CP commands, type
> HELP CPCMDS.
>  
> Other useful documentation and sample programs can be found on MAINT 19D,
> accessed as your U disk.
>  
> For more details, type HELP WELCOME ( MORE
>  
> For information on building the CP or CMS nucleus, read SYSPROG MEMO.
> Ready; T=0.02/0.06 20:28:12
> cmsacc
> ACC 093 B/B
> '093' REPLACES ' B (094) '
> B (093) R/O
> ACC 193 C/C
> C (193) R/O
> ACC 393 D/D
> '393' REPLACES ' D (194) '
> D (393) R/O
> ACC 190 E/E
> '190' REPLACES ' E (294) '
> E (190) R/O
> 190 ALSO = S-DISK
> Ready; T=0.01/0.04 20:29:17
> l rex* * a
> REXXTEST EXEC     A1
> Ready; T=0.01/0.01 20:35:20
> rexxtest
> Unknown CP/CMS command
> dmsrex rexxtest
> Unknown CP/CMS command.

 ... Mark A. Stevens

**Comment by marXtevens** [comment]
I also logged on and did not run CMSACC ...

> L MAINT CPCMS
> DASD 190 LINKED R/W; R/O BY 003 USERS
> DASD 194 LINKED R/W; R/O BY 002 USERS
> DASD 19E LINKED R/W; R/O BY 002 USERS
> FILES: 005 RDR, 107 PRT,  NO PUN
> LOGON AT 20:38:42 GMT THURSDAY 02/11/21
> CMS VERSION 6.0 - 03/11/18 19:50
>  
> Y (19E) R/O
> GCCLIB Version 0.8.3
> GCC ANCHOR Address is 0xe9b000 saved in NUCON at 0x468
> THE FOLLOWING NAMES ARE UNDEFINED:
>  STDIN    STDERR   GETCHAR  @@SIGIGN STDOUT   PUTCHAR
> SYSPROF Error loading BREXX with RESLIB
> U (19D) R/O
> B (094) R/O
> D (194) R/O
> E (294) R/O
> F (394) R/O
>  
> +-----------------------------------------------------------------------------+
> |          Welcome to VM/370 and VM/380 "SixPack" version 1.3!                |
> +-----------------------------------------------------------------------------+
>  
> For a list of CMS commands, type HELP CMSCMDS.  For a list of CP commands, type
> HELP CPCMDS.
>  
> Other useful documentation and sample programs can be found on MAINT 19D,
> accessed as your U disk.
>  
> For more details, type HELP WELCOME ( MORE
>  
> For information on building the CP or CMS nucleus, read SYSPROG MEMO.
> Ready; T=0.02/0.07 20:38:46
> l dmsrex* * *
> Ready(00028); T=0.01/0.01 20:42:57
> l rex* * a
> REXXTEST EXEC     A1
> Ready; T=0.01/0.01 20:43:10
> rexxtest
> Unknown CP/CMS command
> rmsrex rexxtest
> Unknown CP/CMS command

**Comment by adesutherland** [comment]
Welcome!

The log indicates that GCCLIB loaded fine, but that BREXX didn't. It sounds like an old version might still be hanging around (hence the missing symbols)?

MAINT 190 should have brexx text which is loaded resident, and also a brexx module.

access 190 z 
tape load brexx module z
tape rew 
tape load brexx text z 

Do you mind double checking these?

Also try "brexx rexxtest".

Let me know!

Thanks

Adrian

**Comment by marXtevens** [comment]
That's got it!  Has to be User Error, yet again.I wonder if HAO would work like/as well as herccontrol?

> L MAINT
> ENTER PASSWORD:
>  
> DASD 190 LINKED R/W; R/O BY 003 USERS
> DASD 194 LINKED R/W; R/O BY 002 USERS
> DASD 19E LINKED R/W; R/O BY 002 USERS
> FILES: 006 RDR, 107 PRT,  NO PUN
> LOGON AT 23:45:36 GMT THURSDAY 02/11/21
> CMS VERSION 6.0 - 03/11/18 19:50
>  
> Y (19E) R/O
> GCCLIB Version 0.8.3
> GCC ANCHOR Address is 0xe9b000 saved in NUCON at 0x468
> BREXX Version 0.9.11
> BREXX Entry Address is 0xe99bf0 saved in NUCON at 0x90
> U (19D) R/O
> B (094) R/O
> D (194) R/O
> E (294) R/O
> F (394) R/O
>  
> +-----------------------------------------------------------------------------+
> |          Welcome to VM/370 and VM/380 "SixPack" version 1.3!                |
> +-----------------------------------------------------------------------------+
> 
> For a list of CMS commands, type HELP CMSCMDS.  For a list of CP commands, type
> HELP CPCMDS.
>  
> Other useful documentation and sample programs can be found on MAINT 19D,
> accessed as your U disk.
>  
> For more details, type HELP WELCOME ( MORE
>  
> For information on building the CP or CMS nucleus, read SYSPROG MEMO.
> Ready; T=0.02/0.07 23:45:42

**Comment by marXtevens** [comment]
Well I fixed the installation problem. Went away for a while. Came back to try a Rexx program (per your request), and I get a Specification Exception.

> L MAINT
> ENTER PASSWORD:
>  
> DASD 190 LINKED R/W; R/O BY 003 USERS
> DASD 194 LINKED R/W; R/O BY 002 USERS
> DASD 19E LINKED R/W; R/O BY 002 USERS
> FILES: 008 RDR, 107 PRT,  NO PUN
> LOGON AT 03:09:42 GMT FRIDAY 02/12/21
> CMS VERSION 6.0 - 03/11/18 19:50
>  
> Y (19E) R/O
> GCCLIB Version 0.8.3
> GCC ANCHOR Address is 0xe9b000 saved in NUCON at 0x468
> BREXX Version 0.9.11
> BREXX Entry Address is 0xe99bf0 saved in NUCON at 0x90
> U (19D) R/O
> B (094) R/O
> D (194) R/O
> E (294) R/O
> F (394) R/O
>  
> +-----------------------------------------------------------------------------+
> |          Welcome to VM/370 and VM/380 "SixPack" version 1.3!                |
> +-----------------------------------------------------------------------------+
>  
> For a list of CMS commands, type HELP CMSCMDS.  For a list of CP commands, type
> HELP CPCMDS.
>  
> Other useful documentation and sample programs can be found on MAINT 19D,
> accessed as your U disk.
>  
> For more details, type HELP WELCOME ( MORE
>  
> For information on building the CP or CMS nucleus, read SYSPROG MEMO.
> Ready; T=0.02/0.06 03:09:47
> brexx rexxtest
>  
> Beginning smoke test...
>  
> Phase 1: Instructions
> Testing ADDRESS...
> DMSITP141T SPECIFICATION EXCEPTION OCCURRED AT 000005 IN ROUTINE BREXX.
> CMS

**Comment by adesutherland** [comment]
Do you mind uploading the rexxtest program here? Thanks

The problem we have (and this is my bad as I had not thought this through before posting - I fear I have wasted your time) is that we have some mods that were required to get VM/370 and BREXX to behave like REXX and later version of CMS. And a big area was around the way ADDRESS works. I think this is the problem you are running into. You may want to see how the REXX works in other areas but I appreciate that without ADDRESS working it is kind of useless!

You may want to trial the functionality in the pre-patched release here https://github.com/adesutherland/vm-370/releases/tag/v1.4.31 in the vm370 zip file. This will at least tell you if you want to invest more time :-)

If you do we (well @BobBolch) will help you with the required mods - moreover Bob is working on a new release methodology and vm/370 community edition ...

Apologies if this is not helpful!

Adrian

**Comment by marXtevens** [comment]
No I don't mind at all. I'm in this for the long haul now that I am retired. I'm also trying to help in a few other areas, being a guinea pig (if it is still socially correct to pick on the little critters.) 

VM/SP was and is my favorite OS. 

I have noticed service seems a bit fractured, with each one doing it his/her way. I have to admit, I'm used to PUTs, or at least my memory is.

Attached is the REXXTEST EXEC, as a zipped AWS, copied to tape using TAPE DUMP.
[2021-02-12.maint.rexxtext.aws.zip](https://github.com/adesutherland/CMS-370-BREXX/files/5972389/2021-02-12.maint.rexxtext.aws.zip)

 ... Mark A. Stevens

**Comment by adesutherland** [comment]
Great.

Just clarifying one thing, Bob is very much supporting Dave W - we are all working for one edition of VM/370, the fragmentation we seem to have is merely caused by the tactical necessity to share work in progress, if that makes sense.

**Comment by marXtevens** [comment]
The comment is not meant to be derogatory towards anyone. It is an observation of the installation of products, and application of service, that varies, per the person working on it. 

I f you need any other files, or need me to do something, please let me know.

 ... Mark A. Stevens

**Comment by adesutherland** [comment]
I didn't interpret anything negative about your comment!

Please have a look at the VM distribution and see if it's REXX works for you.

Then we can talk mods!

Adrian

**Comment by marXtevens** [comment]
Which distribution, please? I'm working with VM/370 1.3 beta3 from:
http://www.smrcc.org.uk/members/g4ugm/SixPack-1.3.Beta.htm

**Comment by adesutherland** [comment]
vm370.zip @ https://github.com/adesutherland/vm-370/releases/tag/v1.4.31

This is the 6pack 1.3 Beta 3 with BREXX and related MODS installed

Adrian

**Comment by marXtevens** [comment]
Adrian,
I copied my 1.3 beta 3 configuration and other files to a new directory (1.4.31) and backed up those disks and put yours into play, and created shadows. Sorry for the delay in responding, as life, as usual got in the way.
[xmas@vm370dev VM_370_1.4.31]$ unzip -v vm370.zip
Archive:  vm370.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 7194635  Defl:N  5157791  28% 02-04-2021 08:45 517592ff  vm3350-6.6f0.cckd
25179448  Defl:N 24327432   3% 02-04-2021 08:45 6c147fa7  vm3350-1.141.cckd
15991501  Defl:N 14656811   8% 02-04-2021 08:45 6f5c9f68  vm3350-4.440.cckd
28368275  Defl:N 26933201   5% 02-04-2021 08:45 a14a5570  vm3350-5.540.cckd
12509514  Defl:N 11362119   9% 02-04-2021 08:45 f7ab4470  vm3350-3.34f.cckd
27391495  Defl:N 26418329   4% 02-04-2021 08:45 194deb3a  vm3350-2.241.cckd
--------          -------  ---                            -------
116634868         108855683   7%                            6 files
[xmas@vm370dev VM_370_1.4.31]$ 

The old, then the new files.
[xmas@vm370dev 1.4.31]$ ls -l disks.orig/*
-rw-rw-r--. 1 xmas xmas   136769 Jan  8  2018 disks.orig/mcat01.3350.cckd
-rw-rw-r--. 1 xmas xmas 14622072 Jan  8  2018 disks.orig/sysres.3350.cckd
-rw-rw-r--. 1 xmas xmas 25921290 Feb  9 20:16 disks.orig/vm3350-1.141.cckd
-rw-rw-r--. 1 xmas xmas 28118239 Jan  8  2018 disks.orig/vm3350-2.241.cckd
-rw-rw-r--. 1 xmas xmas 11861542 Jan  8  2018 disks.orig/vm3350-3.34f.cckd
-rw-rw-r--. 1 xmas xmas 16669025 Jan  8  2018 disks.orig/vm3350-4.440.cckd
-rw-rw-r--. 1 xmas xmas 26844531 Jan  8  2018 disks.orig/vm3350-5.540.cckd
-rw-rw-r--. 1 xmas xmas  6601563 Jan  8  2018 disks.orig/vm3350-6.6f0.cckd
-rw-r-----. 1 xmas xmas     3678 Feb  9 20:44 disks.orig/vm3350-7.6f1.cckd
-rw-r-----. 1 xmas xmas     3678 Feb  9 20:44 disks.orig/vm3350-8.6f2.cckd
-rw-r-----. 1 xmas xmas     3678 Feb 10 14:18 disks.orig/vm3350-9.441.cckd
-rw-r-----. 1 xmas xmas     3678 Feb 10 14:18 disks.orig/vm3350-A.442.cckd

disks.orig/shadows:
total 29660
-rw-rw-r--. 1 xmas xmas 5989933 Feb 19 20:16 vm3350-11
-rw-rw-r--. 1 xmas xmas 4885678 Feb 19 20:16 vm3350-21
-rw-rw-r--. 1 xmas xmas 6663662 Feb 19 20:16 vm3350-31
-rw-rw-r--. 1 xmas xmas 4615694 Feb 19 20:16 vm3350-41
-rw-rw-r--. 1 xmas xmas 6874647 Feb 19 20:16 vm3350-51
-rw-rw-r--. 1 xmas xmas 1318783 Feb 19 20:16 vm3350-61
-rw-rw-r--. 1 xmas xmas    1288 Feb 19 20:16 vm3350-71
-rw-rw-r--. 1 xmas xmas    1288 Feb 19 20:16 vm3350-81
-rw-r-----. 1 xmas xmas    1288 Feb 19 20:16 vm3350-91
-rw-r-----. 1 xmas xmas    1288 Feb 19 20:16 vm3350-A1
[xmas@vm370dev 1.4.31]$ ls -l disks/*
-rw-r--r--. 1 xmas xmas 25179448 Feb  4 08:45 disks/vm3350-1.141.cckd
-rw-r--r--. 1 xmas xmas 27391495 Feb  4 08:45 disks/vm3350-2.241.cckd
-rw-r--r--. 1 xmas xmas 12509514 Feb  4 08:45 disks/vm3350-3.34f.cckd
-rw-r--r--. 1 xmas xmas 15991501 Feb  4 08:45 disks/vm3350-4.440.cckd
-rw-r--r--. 1 xmas xmas 28368275 Feb  4 08:45 disks/vm3350-5.540.cckd
-rw-r--r--. 1 xmas xmas  7194635 Feb  4 08:45 disks/vm3350-6.6f0.cckd

disks/shadows:
total 120
-rw-r-----. 1 xmas xmas 50263 Feb 22 21:50 vm3350-11
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-12
-rw-r-----. 1 xmas xmas  9292 Feb 22 21:50 vm3350-21
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-22
-rw-r-----. 1 xmas xmas 17574 Feb 22 21:50 vm3350-31
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-32
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-41
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-42
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-51
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-52
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-61
-rw-r-----. 1 xmas xmas  1288 Feb 22 21:50 vm3350-62
[xmas@vm370dev 1.4.31]$ 

 The system IPLs fine, but I see no messages concerning GCC, nor BREXX during MAINT's login.
L MAINT
ENTER PASSWORD:
 
DASD 190 LINKED R/W; R/O BY 003 USERS
DASD 194 LINKED R/W; R/O BY 002 USERS
DASD 19E LINKED R/W; R/O BY 002 USERS
FILES: 006 RDR, 027 PRT,  NO PUN
LOGON AT 03:55:59 GMT TUESDAY 02/23/21
CMS VERSION 6.0 DOCKER 1.4.31
 
Y (19E) R/O
U (19D) R/O
B (094) R/O
D (194) R/O
E (294) R/O
F (394) R/O
 
+-----------------------------------------------------------------------------+
|          Welcome to VM/370 and VM/380 "SixPack" version 1.3!                |
+-----------------------------------------------------------------------------+
 
For a list of CMS commands, type HELP CMSCMDS.  For a list of CP commands, type
HELP CPCMDS.
 
Other useful documentation and sample programs can be found on MAINT 19D,
accessed as your U disk.
 
For more details, type HELP WELCOME ( MORE
 
For information on building the CP or CMS nucleus, read SYSPROG MEMO.
Ready; T=0.01/0.05 03:56:02
 
and PROFILE EXEC looks like this.
type profile exec a
 
&CONTROL OFF NOMSG
CP SPOOL PUN *
CP SPOOL PRT *
GLOBAL TXTLIB PLILIB CMSLIB COB360R FORTLIB SNOBOL4 TSOLIB
GLOBAL MACLIB CMSLIB OSMACRO OSMACRO1 TSOMAC OS360
CP SET  PF12 RETRIEVE
CP SET  PF3 IMMED FILE
CP SET  PF7 IMMED UP 8
CP SET  PF8 IMMED DOWN 8
ACC 094 B/B
ACC 194 D/D
ACC 294 E/E
ACC 394 F/F
EXEC HELP WELCOME
&BEGTYPE
 
For information on building the CP or CMS nucleus, read SYSPROG MEMO.
&END
&EXIT
 
Ready; T=0.01/0.01 03:57:05
Finally, trying to run REXXTEST EXEC A gets me the same error, as I had originally with my updated 1.3 beta 3 DASD.
l rexxtest exec a (date
Filename Filetype Fm  Format    Recs Blocks     Date    Time
REXXTEST EXEC     A1  V   121    186     11  08/08/10   19:57
Ready; T=0.01/0.01 04:03:43
brexx rexxtest
DMSITP141T OPERATION EXCEPTION OCCURRED AT 000006 IN ROUTINE BREXX.
CMS
Yours in confusion,
 ... Mark A. Stevens
-----Original Message-----

**Comment by BobBolch** [comment]
Hi Mark,
The BREXX interpreter is initialized by the SYSPROF EXEC and the Sixpack
used an override version of that on the MAINT ID to suppress BREXX
initialization. BREXX should function on other IDs like CMSUSER. Also, you
can just issue REXXTEST as a command, You do not need to say BREXX REXXTEST.

Bob Bolch

**Comment by adesutherland** [comment]
Hi Mark - is it possible for you to post REXXTEST EXEC as text (perhaps via IND$FILE) - that will save me a bit of trouble extracting it. If not let me know and I will mount the tape you posted later today.

Cheers

Adrian

**Comment by marXtevens** [comment]
Gentlemen,

I submit REXXTEST EXEC is on the wrong account, and should be moved to CMSUSER. 

Also, having moved the little bugger to CMSUSER, it runs quite well, as you can see below.

That I can't run the test program on MAINT, just added one more hurdle none of us needed. Wasted my time, and I wasted yours. Since I have your attention, does it make sense to add the extra code to MAINT's PROFILE EXEC, so it can run Rexx? Or, should it just be moved to CMSUSER and "we" live without Rexx on MAINT?

I'm trying to find common ground, if possible. This has been "interesting" enough to make me wonder, if I should try writing a Rexx interpreter in PL/I, and/or Assembler, languages native to IBM and VM/370.

Thanks for putting up with me. I should be here for the long haul.

 ... Mark A. Stevens

> Hi Mark,
> The BREXX interpreter is initialized by the SYSPROF EXEC and the Sixpack
> used an override version of that on the MAINT ID to suppress BREXX
> initialization. BREXX should function on other IDs like CMSUSER. Also, you
> can just issue REXXTEST as a command, You do not need to say BREXX REXXTEST.
> 
> Bob Bolc

> Hi Mark - is it possible for you to post REXXTEST EXEC as text (perhaps via IND$FILE) - that will save me a bit of trouble extracting it. If not let me know and I will mount the tape you posted later today.
> 
> Cheers
> 
> Adrian

> q cmsuser
> CMSUSER  - 1C1
> Ready; T=0.01/0.01 14:04:33
> q n
> MAINT    - 1C0, OPERATOR - 009, CMSBATCH - DSC, CPWATCH  - DSC
> CMSUSER  - 1C1
> Ready; T=0.01/0.01 14:04:40
> tape rew
> Ready; T=0.01/0.01 14:05:06
> tape load * * a
>  LOADING.....
>  REXXTEST EXEC     A1
>  END-OF-FILE OR END-OF-TAPE
> Ready; T=0.01/0.01 14:05:17
> rexxtest
>  
> Beginning smoke test...
>  
> Phase 1: Instructions
> Testing ADDRESS...
>     13 *-* ADDRESS "SYSTEM" "CP QUERY TIME"
>        +++ RC(-3) +++
> Testing ARG...
>   Argument 1 is  or
>   Argument 2 is  or
>   Argument 3 is  or
>   Argument 4 is  or
>   Argument 5 is  or
> CALL       verified.
> PROCEDURE  verified.
> Testing QUEUE...
> Testing PUSH...
> Testing PARSE PULL...
> PARSE PULL verified.
> QUEUE      verified.
> Testing SIGNAL...
> SIGNAL     verified.
>  
> Phase 2: Operators and Variables
> Assignment verified.
> Stems      verified.
>  
> Phase 3: Built-In Functions
> Abbrev     verified.
> Abs        verified.
> Address()  returned: CMS
> Arg()      returned: 0
> B2x        verified.
> BitAnd     verified.
> BitOr      verified.
> BitXor     verified.
> C2D        verified.
> C2X        verified.
> Center     verified.
> ChangeStr  verified.
> Compare    verified.
> Condition  ignored.
> Copies     verified.
> CountStr   verified.
> D2C        verified.
> D2X        verified.
> DataType   verified.
> Date()     returned: 23 Feb 2021
> DelStr     verified.
> DelWord    verified.
> Digits()   returned: 9
> ErrorText  verified.
> Form()     returned: SCIENTIFIC
> Format     verified.
> Fuzz()     returned: 0
> Insert     verified.
> LastPos    verified.
> Left       verified.
> Length     verified.
> Max        verified.
> Min        verified.
> Overlay    verified.
> Pos        verified.
> Queued     verified.
> Random()   returned: 803
> Reverse    verified.
> Right      verified.
> Sign       verified.
> SourceLine /* Robert O'Hara, Redmond, Washington, June 2010.                 
>                              */
> Space      verified.
> Strip      verified.
> Substr     verified.
> SubWord    verified.
> Symbol     verified.
> Time()     returned: 14:06:40
> Trace()    returned: N
> Translate  verified.
> Trunc      ***ERROR***
> Userid()   returned: CMSUSER
> Value      verified.
> Verify     verified.
> Word       verified.
> WordIndex  verified.
> WordLength verified.
> WordPos    verified.
> Words      verified.
> X2B        verified.
> X2C        verified.
> XRange     verified.
>  
> Smoke test is complete.
> Ready; T=0.13/0.17 14:07:05
> 















                                                            RUNNING   SIXPACK

**Comment by BobBolch** [comment]
Hi Mark,
   REXXTEST EXEC is distributed on the Sixpack. I am recommending that it
be moved to the Y-disk
for the next VM release. Until then, just send a copy to wherever you want
to run it.
   The Sixpack also distributes a SYSPROF EXEC on the MAINT A-disk, which
overrides the version
which loads BREXX when you IPL CMS. Just rename or erase the SYSPROF EXEC
on the MAINT A disk and
REXX will run just fine on MAINT, as far as I know. I run REXX on MAINT and
never saw any problems.
I do not know why the Sixpack developers made the decision to disallow REXX
on MAINT.

Bob Bolch

**Comment by adesutherland** [comment]
> REXXTEST EXEC is distributed on the Sixpack

Sorry Mark I didn't realise it was a file on the sixpack! I can grab a copy myself obviously. Sorry for wasting time.

As for the tests they both seem to be errors in REXXTEST :-)

- Address "System" should be ADDRESS COMMAND
- Trunc does indeed truncate and not round in REXX!

Cheers

Adrian
