### ISSUE TITLE
Question regarding MAKEBUF / DROPBUF functions

### ISSUE THREAD

**Issue by mgrossmann** [adesutherland/CMS-370-BREXX#69]
Hey REXXers :)

I'm not quiet sure what I'm doing wrong while calling MAKEBUF and DROPBUF functions.
What I'm missing here? (btw: DROPBUF returned RC=2)

```rexx
/* REXX */                         
SAY "A) STACK SIZE IS "QUEUED()       /* should be 0 */                              
PUSH "DATA"                             
SAY "B) STACK SIZE IS "QUEUED()       /* should be 1 */     
'MAKEBUF'                               
mystk=rc                                
SAY "C) STACK SIZE IS "QUEUED()       /* should be 0 */     
PARSE EXTERNAL CMD                      
'DROPBUF' mystk                         
SAY "D) STACK SIZE IS "QUEUED()       /* should be 1 */
```
this is the unexpected result
```
Ready; 
bug                         
A) STACK SIZE IS 0          
B) STACK SIZE IS 1          
C) STACK SIZE IS 1          
D) STACK SIZE IS 0          
Ready;  
```
          
/MIkeG

**Comment by BobBolch** [comment]
MAKEBUF does not modify the number of lines in the stack, or reset it.
After the MAKEBUF, the line count in the stack remains 1
After the Parse, the line count in the stack is 0

The use is:
'MAKEBUF';bno=rc

then put stuff on the stack

then, if your EXEC has an error, or ends
remove any lines you added with 'DROPBUF' bno

To avoid pulling lines that don not belong to you:

queued=queued()
'MAKEBUF';bno = rc
put some lines on the stack
Do queued()-queued
    Parse pull line
   process line this code added to the stack
End
'DROPBUF" bno

**Comment by RossPatterson** [comment]
Bob Bolch's answer of 2021-04-05 is correct.  This is not a bug.
