### ISSUE TITLE
Uninitialised variable should have its name (uppercase) as its value 

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CMS-370-BREXX#9]
Executing gives 

SAY hello

Generates an error 'REXX:- uninitialized variable, or failure in system service'

But should it not just say "HELLO"?!

**Comment by rvjansen** [comment]
It should.

René.

**Comment by adesutherland** [comment]
It was just **rexxtry exec** having **signal on novalue**, which I have now removed as it was very irritating!
